version: 2.1

workflows:
  build:
    jobs:
      - lint
      - flow
      - test:
          version: 12-stretch
          name: 12-stretch
          requires:
            - lint
            - flow
      - test:
          version: lts-stretch
          name: lts-stretch
          requires:
            - lint
            - flow
      - test:
          version: current-stretch
          name: current-stretch
          requires:
            - lint
            - flow

jobs:
  lint:
    docker:
      - image: circleci/node:current-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run lint
          command: npm run lint
          
  flow:
    docker:
      - image: circleci/node:current-stretch

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run flow
          command: npm run flow

  test:
    parameters:
      version:
        type: string

    docker:
      - image: circleci/node:<< parameters.version >>

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm ci
      - run: npm run jest
