name: Run VIP-cli tests
on:
  pull_request

jobs:
  Run_windows_tests:
    name: Run Windows Tests
    runs-on: windows-latest
    steps:
      # To prevent issues with fixtures on Windows tests
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true
          path: vip

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci
        working-directory: vip

      - name: Unit Tests
        working-directory: vip
        run: npm run jest
      
      - name: Test Command line
        working-directory: vip
        run: |
          node ./dist/bin/vip app
